# Postman service configuration file.

[service]
# The service name might be shared among all instances
# of the same service.
name = "auth"

[broker]
# Connection string. This must include the username
# and password (if any), the host and the port.
uri = "amqp://rabbitmq:rabbitmq@rabbitmq:5672"

[http]
listen_to_hosts = [] # Empty list will listen to all hosts
# If you need just to listen to a single or a few IP addresses:
#listen_to_hosts = ["127.0.0.1", "<otherip>"]
listen_port = 8130
# We'll forward all incoming requests as HTTP calls to this host.
fwd_host = "http://auth_2:80"

[dashboard]
enabled = true
listen_to_hosts = [] # Empty list will listen to all hosts
# If you need just to listen to a single or a few IP addresses:
#listen_to_hosts = ["127.0.0.1", "<otherip>"]
listen_port = 18130

[message]
# Time in seconds we will wait for the response of the message.
#receive_timeout = 10


